[package]
name = "okapi-token-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.18.4"
spl-token = { version = "4.0.0", features = ["no-entrypoint"] }